### ISSUE TITLE
What does the stats mean

### ISSUE THREAD

**Issue by suoigwg** [semihalev/gin-stats#1]
Hi
I use your code in my project and it gives me 
`
{
"gin.latency": {
"15m.rate": 5.969543515457789,
"1m.rate": 15.35357001761647,
"5m.rate": 11.708787908105679,
"75%": 736041.5,
"95%": 2626162.4499999993,
"99%": 4531992.170000003,
"99.9%": 2069183743.5530078,
"count": 6671,
"max": 2130792702,
"mean": 2743824.8667315175,
"mean.rate": 14.52805760753786,
"median": 330938,
"min": 87153,
"stddev": 66409879.13347689
},
"gin.request": {
"15m.rate": 5.969543515457789,
"1m.rate": 15.35357001761647,
"5m.rate": 11.708787908105679,
"count": 6671,
"mean.rate": 14.528056446129751
},
"gin.status.200": {
"15m.rate": 2.0979988944182595,
"1m.rate": 5.36152600204981,
"5m.rate": 4.02353999457537,
"count": 2250,
"mean.rate": 4.900034674082915
},
"gin.status.400": {
"15m.rate": 19.96579312884689,
"1m.rate": 0.019302671537436266,
"5m.rate": 7.399549104583825,
"count": 269,
"mean.rate": 0.5942917914181584
},
"gin.status.404": {
"15m.rate": 3.9310083627746844,
"1m.rate": 9.989635568590261,
"5m.rate": 7.571177956301687,
"count": 4152,
"mean.rate": 9.137409850737969
}
}
`
I wonder what 15m.rate, 1m.rate, 5m.rate means(and their metrics and units)
Thanks

**Comment by semihalev** [comment]
these are average request per second, 1 minute, 15 minutes, 5 minutes also count is simple counter, total requests, mean is average response time, max is longest response time, min is shortest response time.
